---

- name: Extra Packages for Enterprise Linux (EPEL)
  dnf:
    name:
      - epel-release
    state: latest

- name: Enable EPEL group
  shell: >-
    dnf --enablerepo=epel group

- name: Install core DNF plugins
  dnf:
    name:
      - dnf-plugins-core
    state: latest

- name: Install/update system-related packages
  dnf:
    name:
      - bash-completion
      - bzip2
      - dkms
      - elfutils-libelf-devel
      - gcc
      - kernel-devel
      - kernel-headers
      - make
      - perl
      - sshpass
    state: latest

- name: Install/update system-related modules
  dnf:
    name:
      - "@base-x"
      - "@Container management"
      - "@Development tools"
      - "@Xfce"
    state: latest

- name: "Add yum repository: {{ item.name }}"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description" }}
    file: "{{ item.file }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck | bool }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck | bool }}"
    gpgkey: "{{ item.gpgkey }}"
    sslverify: "{{ item.sslverify | bool }}"
    sslcacert: "{{ item.sslcacert }}"
    enabled: "{{ item.enabled | bool }}"
  loop_control:
    label: "{{ item.name }}"
  loop: "{{ yum_repos }}"

- name: Import the RPM keys
  rpm_key:
    key: "{{ item.gpgkey }}"
    state: present
  loop_control:
    label: "{{ item.name }}"
  loop: "{{ yum_repos }}"

- name: Install/update display-related packages
  dnf:
    name:
      - cuda-drivers.x86_64
      - nvidia-driver.x86_64
      - nvidia-settings.x86_64
    state: latest

- name: Install/update gui-related packages
  dnf:
    name:
      - gnome-theme-extras
      - papirus-icon-theme
      - xfce4-about
      - xfce4-appfinder
      - xfce4-panel
      - xfce4-power-manager
      - xfce4-pulseaudio-plugin
      - xfce4-screensaver
      - xfce4-screenshooter
      - xfce4-session
      - xfce4-settings
      - xfce4-terminal
      - xfce4-whiskermenu-plugin
    state: latest

- name: Install extra containerization packages
  dnf:
    name:
      - podman
      - podman-compose
    state: latest

- name: Install VirtualBox
  dnf:
    name:
      - "VirtualBox-{{ virtualbox_version }}"
    state: present

- name: Install/update GitKraken
  dnf:
    name: https://release.gitkraken.com/linux/gitkraken-amd64.rpm
#    disable_gpg_check: yes
    state: present

- name: Install/update Zoom
  dnf:
    name: https://zoom.us/client/latest/zoom_x86_64.rpm
    state: present

- name: Install/update other packages
  dnf:
    name:
      - 1password
      - code
      - conda
      - firefox
      - git
      - google-chrome-stable
      - keepassxc
      - packer
      - slack
      - terraform
      - vagrant
      - vault
      - wireshark
    state: latest